Core and heatmap
slamdata/purescript-leafletjs pull request #1
Opened 2017-04-28 15:40 UTC by cryogenian

This is the very basic thing to leaflet.js 

I made this because updating existing lib from 0.7 -> 0.11 and generalizing it has almost same complexety. 

Also ported Leaflet/Leaflet.heat with funny `Ref` emitting code. 

@natefaubion Please take a look.

2017-05-01 21:31 UTC, natefaubion requested changes

2017-05-01 21:31 UTC, natefaubion commented on src/Leaflet/Core/Plugin.js
> +        var res = {value: Nothing};
We shouldn't be making assumptions about the representation of refs. We should just do this stuff in PS land.

```purescript
onAddRemove init finish l lf = liftEff do
  ref <- newRef Nothing
  let
    onAddFn = mkFn2 \a b -> do
      val <- init a b
      writeRef ref val
    onRemoveFn = ...
  runFn6 onAddRemove_ ..
  pure ref
```

2017-05-01 21:31 UTC, natefaubion commented on src/Leaflet/Core/Layer.purs
> +  ⇒ Union r1 r2 (T.PolylineConf ())
So on stuff like this, there are no _required_ options for the confs, right? For any of them `{}` is a valid configuration?

2017-05-02 09:17 UTC, cryogenian commented on src/Leaflet/Core/Layer.purs
> +  ⇒ Union r1 r2 (T.PolylineConf ())
Yep, empty option map is valid

2017-05-02 09:18 UTC, cryogenian commented on src/Leaflet/Core/Plugin.js
> +        var res = {value: Nothing};
:+1:

2017-05-02 14:56 UTC, cryogenian commented
I've abstracted `Ref`, so, js doesn't know how refs work. Although creation and writing to it are located in js code. 
@natefaubion Is this ok? I can create `Ref` in PS and leave only modifying in JS or just remove all this ref stuff at all until we actually need it

2017-05-02 15:00 UTC, natefaubion commented
The main thing is just if there is a _need_ for it to be in JS. We shouldn't put anything in JS that can be easily done in PS. At a glance, it looks like there is no reason that `addRemove_` can't just take regular callbacks, and we can do all the `Ref` coordination in PS. Is that the case, or does the FFI rely on the `Ref` business?

2017-05-02 15:06 UTC, cryogenian commented
As far as I understand leaflet code, `onAdd` _should_ (contract or whatever) return `this`, so modification of of ref should be done in js. Although instead of `Nothing` and `newRef` I can put there ref with `Nothing` :D

2017-05-02 15:10 UTC, cryogenian commented
Ah! Yep, `init` must be called in JS handler because leaflet/layer state could change

2017-05-02 15:22 UTC, cryogenian commented
I think this will work

2017-05-02 15:35 UTC, natefaubion approved these changes

2017-05-02 15:56 UTC, merged