control
slamdata/purescript-leafletjs pull request #2
Opened 2017-06-01 14:50 UTC by cryogenian

Adding control and couple event operations

@beckyconning please take a look

2017-06-05 11:53 UTC, cryogenian commented
Seems that @beckyconning is very busy, @garyb maybe you can take a look at this?

2017-06-05 21:48 UTC, garyb requested changes

2017-06-05 21:48 UTC, garyb commented on bower.json
> +  "name": "purescript-leafletjs",
Was this intentional? :)

2017-06-05 21:48 UTC, garyb commented on src/Leaflet/Core/Layer.js
> +            console.log(ev);
`console.log`

2017-06-05 21:49 UTC, garyb commented on bower.json
> +  "name": "purescript-leafletjs",
Oh, I see from the other PR it was. We should perhaps rename this repo to match the bower name then?

2017-06-06 13:47 UTC, cryogenian commented on bower.json
> +  "name": "purescript-leafletjs",
:+1:

2017-06-06 13:51 UTC, cryogenian commented
+ Removed `console.log`
+ Renamed the repo

2017-06-06 13:51 UTC, garyb approved these changes

2017-06-06 14:20 UTC, merged